# Generated by Django 4.1.3 on 2023-01-31 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_team_alter_memberteam_member'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting reply'), ('accepted', 'Accepted'), ('refused', 'refused')], default='awaiting', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='matches.game')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='members.memberteam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
