# Generated by Django 4.1.3 on 2022-12-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_generate_slugs_for_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(),
        ),
    ]
