# Generated by Django 4.1.3 on 2022-12-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_club_slug'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='club.club'),
        ),
    ]
