# Generated by Django 4.1.3 on 2022-12-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_memberteam_member_alter_memberteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ManyToManyField(related_name='teams', through='members.MemberTeam', to='members.team'),
        ),
        migrations.AlterField(
            model_name='memberteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.team'),
        ),
    ]
